# Generated by Django 3.0.7 on 2020-06-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200611_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_comment',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
