# Generated by Django 3.0.7 on 2020-06-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_city_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='city',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='city',
            new_name='country',
        ),
    ]
