# Generated by Django 3.0.7 on 2020-06-15 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200615_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Place'),
        ),
    ]
