# Generated by Django 3.0.7 on 2020-06-18 18:11

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200618_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True),
        ),
        migrations.DeleteModel(
            name='ImagePost',
        ),
    ]
