# Generated by Django 3.0.7 on 2020-06-22 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20200623_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Country'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post_pics', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Place'),
        ),
    ]
