# Generated by Django 3.0.7 on 2020-06-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20200623_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, verbose_name='Nội dung'),
        ),
    ]
