# Generated by Django 3.0.7 on 2020-06-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20200701_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(default=None, upload_to='post_pics', verbose_name='images'),
        ),
    ]
