# Generated by Django 3.0.7 on 2020-06-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20200701_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='images',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default=None, upload_to='post_pics', verbose_name='image'),
        ),
    ]
